// Code generated by MockGen. DO NOT EDIT.
// Source: account_provider.go
//
// Generated by this command:
//
//	mockgen -package service_mocks -source account_provider.go -destination mocks/business_mocks/account_provider_mock.go
//

// Package service_mocks is a generated GoMock package.
package service_mocks
