services:
  postgres:
    image: postgres:15
    container_name: ledger_postgres
    environment:
      POSTGRES_DB: ledgerdb
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      TZ: Asia/Kolkata          # set system timezone
      PGTZ: Asia/Kolkata        # set postgres timezone
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql